//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANT.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ANT.Lang.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to favorites.
        /// </summary>
        public static string AddedToFavorite {
            get {
                return ResourceManager.GetString("AddedToFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Date.
        /// </summary>
        public static string Airing {
            get {
                return ResourceManager.GetString("Airing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Translate.
        /// </summary>
        public static string AutomaticTranslate {
            get {
                return ResourceManager.GetString("AutomaticTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast.
        /// </summary>
        public static string Broadcast {
            get {
                return ResourceManager.GetString("Broadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue.
        /// </summary>
        public static string Catalogue {
            get {
                return ResourceManager.GetString("Catalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change theme.
        /// </summary>
        public static string ChangeTheme {
            get {
                return ResourceManager.GetString("ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want clear the list? This action cannot be undone..
        /// </summary>
        public static string ClearCannotBeUndone {
            get {
                return ResourceManager.GetString("ClearCannotBeUndone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear recent list.
        /// </summary>
        public static string ClearRecentList {
            get {
                return ResourceManager.GetString("ClearRecentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect.
        /// </summary>
        public static string Deselect {
            get {
                return ResourceManager.GetString("Deselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration per episode:.
        /// </summary>
        public static string DurationPerEpisode {
            get {
                return ResourceManager.GetString("DurationPerEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available, how about contribute?.
        /// </summary>
        public static string EpisodeData {
            get {
                return ResourceManager.GetString("EpisodeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episodes.
        /// </summary>
        public static string Episodes {
            get {
                return ResourceManager.GetString("Episodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, please reenter this page.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizing....
        /// </summary>
        public static string Finalizing {
            get {
                return ResourceManager.GetString("Finalizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fridays.
        /// </summary>
        public static string Fridays {
            get {
                return ResourceManager.GetString("Fridays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen.
        /// </summary>
        public static string LastSeen {
            get {
                return ResourceManager.GetString("LastSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading more data....
        /// </summary>
        public static string LoadingMoreData {
            get {
                return ResourceManager.GetString("LoadingMoreData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See at MAL.
        /// </summary>
        public static string MAL {
            get {
                return ResourceManager.GetString("MAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mondays.
        /// </summary>
        public static string Mondays {
            get {
                return ResourceManager.GetString("Mondays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string MultiSelect {
            get {
                return ResourceManager.GetString("MultiSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        public static string NoDataAvailable {
            get {
                return ResourceManager.GetString("NoDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing for now.
        /// </summary>
        public static string NothingForNow {
            get {
                return ResourceManager.GetString("NothingForNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string Pictures {
            get {
                return ResourceManager.GetString("Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently seen.
        /// </summary>
        public static string Recents {
            get {
                return ResourceManager.GetString("Recents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed from favorites.
        /// </summary>
        public static string RemovedFromFavorite {
            get {
                return ResourceManager.GetString("RemovedFromFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturdays.
        /// </summary>
        public static string Saturdays {
            get {
                return ResourceManager.GetString("Saturdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string SelectAppLang {
            get {
                return ResourceManager.GetString("SelectAppLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select app theme.
        /// </summary>
        public static string SelectAppTheme {
            get {
                return ResourceManager.GetString("SelectAppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sundays.
        /// </summary>
        public static string Sundays {
            get {
                return ResourceManager.GetString("Sundays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursdays.
        /// </summary>
        public static string Thursdays {
            get {
                return ResourceManager.GetString("Thursdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episodes amount:.
        /// </summary>
        public static string TotalEpisodes {
            get {
                return ResourceManager.GetString("TotalEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesdays.
        /// </summary>
        public static string Tuesdays {
            get {
                return ResourceManager.GetString("Tuesdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown broadcast.
        /// </summary>
        public static string UnknownDate {
            get {
                return ResourceManager.GetString("UnknownDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesdays.
        /// </summary>
        public static string Wednesdays {
            get {
                return ResourceManager.GetString("Wednesdays", resourceCulture);
            }
        }
    }
}
