//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANT.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ANT.Lang.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to favorites.
        /// </summary>
        public static string AddedToFavorite {
            get {
                return ResourceManager.GetString("AddedToFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Date.
        /// </summary>
        public static string Airing {
            get {
                return ResourceManager.GetString("Airing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative versions.
        /// </summary>
        public static string AlternativeVersions {
            get {
                return ResourceManager.GetString("AlternativeVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime.
        /// </summary>
        public static string Anime {
            get {
                return ResourceManager.GetString("Anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications(Animes).
        /// </summary>
        public static string AnimeNotifications {
            get {
                return ResourceManager.GetString("AnimeNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animeography.
        /// </summary>
        public static string Animeography {
            get {
                return ResourceManager.GetString("Animeography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App details.
        /// </summary>
        public static string AppDetails {
            get {
                return ResourceManager.GetString("AppDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply filter.
        /// </summary>
        public static string ApplyFilter {
            get {
                return ResourceManager.GetString("ApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        public static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Translate.
        /// </summary>
        public static string AutomaticTranslate {
            get {
                return ResourceManager.GetString("AutomaticTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast.
        /// </summary>
        public static string Broadcast {
            get {
                return ResourceManager.GetString("Broadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build date.
        /// </summary>
        public static string BuildDate {
            get {
                return ResourceManager.GetString("BuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue.
        /// </summary>
        public static string Catalogue {
            get {
                return ResourceManager.GetString("Catalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue selector.
        /// </summary>
        public static string CatalogueSelector {
            get {
                return ResourceManager.GetString("CatalogueSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change theme.
        /// </summary>
        public static string ChangeTheme {
            get {
                return ResourceManager.GetString("ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want clear the list? This action cannot be undone..
        /// </summary>
        public static string ClearCannotBeUndone {
            get {
                return ResourceManager.GetString("ClearCannotBeUndone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear database.
        /// </summary>
        public static string ClearDatabase {
            get {
                return ResourceManager.GetString("ClearDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear favorite list.
        /// </summary>
        public static string ClearFavoriteList {
            get {
                return ResourceManager.GetString("ClearFavoriteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear recent list.
        /// </summary>
        public static string ClearRecentList {
            get {
                return ResourceManager.GetString("ClearRecentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of week.
        /// </summary>
        public static string DayOfWeek {
            get {
                return ResourceManager.GetString("DayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting animes.
        /// </summary>
        public static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected animes will be deleted, do you wish to continue?.
        /// </summary>
        public static string DeletingMessage {
            get {
                return ResourceManager.GetString("DeletingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect.
        /// </summary>
        public static string Deselect {
            get {
                return ResourceManager.GetString("Deselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete {0} database, do you wish to continue?.
        /// </summary>
        public static string DropDatabase {
            get {
                return ResourceManager.GetString("DropDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration per episode:.
        /// </summary>
        public static string DurationPerEpisode {
            get {
                return ResourceManager.GetString("DurationPerEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available, how about contribute?.
        /// </summary>
        public static string EpisodeData {
            get {
                return ResourceManager.GetString("EpisodeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episodes.
        /// </summary>
        public static string Episodes {
            get {
                return ResourceManager.GetString("Episodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New episode today.
        /// </summary>
        public static string EpisodeToday {
            get {
                return ResourceManager.GetString("EpisodeToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, please reenter this page.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fall.
        /// </summary>
        public static string Fall {
            get {
                return ResourceManager.GetString("Fall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite animes.
        /// </summary>
        public static string FavoriteAnimes {
            get {
                return ResourceManager.GetString("FavoriteAnimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite characters.
        /// </summary>
        public static string FavoriteCharacters {
            get {
                return ResourceManager.GetString("FavoriteCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite voice actors.
        /// </summary>
        public static string FavoriteVoiceActors {
            get {
                return ResourceManager.GetString("FavoriteVoiceActors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizing....
        /// </summary>
        public static string Finalizing {
            get {
                return ResourceManager.GetString("Finalizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Airing.
        /// </summary>
        public static string FinishedAiring {
            get {
                return ResourceManager.GetString("FinishedAiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fridays.
        /// </summary>
        public static string Fridays {
            get {
                return ResourceManager.GetString("Fridays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global search.
        /// </summary>
        public static string GlobalSearch {
            get {
                return ResourceManager.GetString("GlobalSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour to notify(estimated hours).
        /// </summary>
        public static string HourToNotify {
            get {
                return ResourceManager.GetString("HourToNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last episode seen.
        /// </summary>
        public static string LastEpisode {
            get {
                return ResourceManager.GetString("LastEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen.
        /// </summary>
        public static string LastSeen {
            get {
                return ResourceManager.GetString("LastSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading more data....
        /// </summary>
        public static string LoadingMoreData {
            get {
                return ResourceManager.GetString("LoadingMoreData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See at MAL.
        /// </summary>
        public static string MAL {
            get {
                return ResourceManager.GetString("MAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mondays.
        /// </summary>
        public static string Mondays {
            get {
                return ResourceManager.GetString("Mondays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string MultiSelect {
            get {
                return ResourceManager.GetString("MultiSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        public static string NoDataAvailable {
            get {
                return ResourceManager.GetString("NoDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing for now.
        /// </summary>
        public static string NothingForNow {
            get {
                return ResourceManager.GetString("NothingForNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started.
        /// </summary>
        public static string NotStarted {
            get {
                return ResourceManager.GetString("NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show adult content.
        /// </summary>
        public static string NSFW {
            get {
                return ResourceManager.GetString("NSFW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch notes.
        /// </summary>
        public static string PatchNotes {
            get {
                return ResourceManager.GetString("PatchNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string Pictures {
            get {
                return ResourceManager.GetString("Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prequels.
        /// </summary>
        public static string Prequels {
            get {
                return ResourceManager.GetString("Prequels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently viewed.
        /// </summary>
        public static string RecentlyViewed {
            get {
                return ResourceManager.GetString("RecentlyViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently seen.
        /// </summary>
        public static string Recents {
            get {
                return ResourceManager.GetString("Recents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations.
        /// </summary>
        public static string Recommendations {
            get {
                return ResourceManager.GetString("Recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry.
        /// </summary>
        public static string Registry {
            get {
                return ResourceManager.GetString("Registry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related.
        /// </summary>
        public static string Related {
            get {
                return ResourceManager.GetString("Related", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed from favorites.
        /// </summary>
        public static string RemovedFromFavorite {
            get {
                return ResourceManager.GetString("RemovedFromFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset filter.
        /// </summary>
        public static string ResetFilter {
            get {
                return ResourceManager.GetString("ResetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturdays.
        /// </summary>
        public static string Saturdays {
            get {
                return ResourceManager.GetString("Saturdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search filters.
        /// </summary>
        public static string SearchFilters {
            get {
                return ResourceManager.GetString("SearchFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string SelectAppLang {
            get {
                return ResourceManager.GetString("SelectAppLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select app theme.
        /// </summary>
        public static string SelectAppTheme {
            get {
                return ResourceManager.GetString("SelectAppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the season.
        /// </summary>
        public static string SelectSeason {
            get {
                return ResourceManager.GetString("SelectSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the year.
        /// </summary>
        public static string SelectYear {
            get {
                return ResourceManager.GetString("SelectYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequels.
        /// </summary>
        public static string Sequels {
            get {
                return ResourceManager.GetString("Sequels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string Shelved {
            get {
                return ResourceManager.GetString("Shelved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiving animes.
        /// </summary>
        public static string Shelving {
            get {
                return ResourceManager.GetString("Shelving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived animes will be unarchived and unarchived will be archived. Archived animes won&apos;t be updated, do you wish to continue?.
        /// </summary>
        public static string ShelvingMessage {
            get {
                return ResourceManager.GetString("ShelvingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrink size.
        /// </summary>
        public static string ShrinkSize {
            get {
                return ResourceManager.GetString("ShrinkSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side story.
        /// </summary>
        public static string SideStory {
            get {
                return ResourceManager.GetString("SideStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort order.
        /// </summary>
        public static string SortOrder {
            get {
                return ResourceManager.GetString("SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin offs.
        /// </summary>
        public static string SpinOffs {
            get {
                return ResourceManager.GetString("SpinOffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring.
        /// </summary>
        public static string Spring {
            get {
                return ResourceManager.GetString("Spring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer.
        /// </summary>
        public static string Summer {
            get {
                return ResourceManager.GetString("Summer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sundays.
        /// </summary>
        public static string Sundays {
            get {
                return ResourceManager.GetString("Sundays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursdays.
        /// </summary>
        public static string Thursdays {
            get {
                return ResourceManager.GetString("Thursdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today animes.
        /// </summary>
        public static string TodayAnimes {
            get {
                return ResourceManager.GetString("TodayAnimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow animes.
        /// </summary>
        public static string TomorrowAnimes {
            get {
                return ResourceManager.GetString("TomorrowAnimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episodes amount:.
        /// </summary>
        public static string TotalEpisodes {
            get {
                return ResourceManager.GetString("TotalEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesdays.
        /// </summary>
        public static string Tuesdays {
            get {
                return ResourceManager.GetString("Tuesdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of sort.
        /// </summary>
        public static string TypeOfSort {
            get {
                return ResourceManager.GetString("TypeOfSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown broadcast.
        /// </summary>
        public static string UnknownDate {
            get {
                return ResourceManager.GetString("UnknownDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animes updated successfully.
        /// </summary>
        public static string UpdatedAnimes {
            get {
                return ResourceManager.GetString("UpdatedAnimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters updated succesfully.
        /// </summary>
        public static string UpdatedCharacters {
            get {
                return ResourceManager.GetString("UpdatedCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice actors updated succesfully.
        /// </summary>
        public static string UpdatedVoiceActors {
            get {
                return ResourceManager.GetString("UpdatedVoiceActors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating animes.
        /// </summary>
        public static string UpdatingAnimes {
            get {
                return ResourceManager.GetString("UpdatingAnimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animes will be updated, internet connection is required. Do you wish to continue?.
        /// </summary>
        public static string UpdatingAnimesMessage {
            get {
                return ResourceManager.GetString("UpdatingAnimesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating characters.
        /// </summary>
        public static string UpdatingCharacters {
            get {
                return ResourceManager.GetString("UpdatingCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters will be updated, internet connection is required. Do you wish to continue?.
        /// </summary>
        public static string UpdatingCharactersMessage {
            get {
                return ResourceManager.GetString("UpdatingCharactersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating voice actors.
        /// </summary>
        public static string UpdatingVoiceActors {
            get {
                return ResourceManager.GetString("UpdatingVoiceActors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice actors will be updated, internet connection is required. Do you wish to continue?.
        /// </summary>
        public static string UpdatingVoiceActorsMessage {
            get {
                return ResourceManager.GetString("UpdatingVoiceActorsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data.
        /// </summary>
        public static string UserData {
            get {
                return ResourceManager.GetString("UserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data location.
        /// </summary>
        public static string UserDataLocation {
            get {
                return ResourceManager.GetString("UserDataLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice acting roles.
        /// </summary>
        public static string VoiceActingRoles {
            get {
                return ResourceManager.GetString("VoiceActingRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice actor.
        /// </summary>
        public static string VoiceActor {
            get {
                return ResourceManager.GetString("VoiceActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice actors.
        /// </summary>
        public static string VoiceActors {
            get {
                return ResourceManager.GetString("VoiceActors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesdays.
        /// </summary>
        public static string Wednesdays {
            get {
                return ResourceManager.GetString("Wednesdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter.
        /// </summary>
        public static string Winter {
            get {
                return ResourceManager.GetString("Winter", resourceCulture);
            }
        }
    }
}
